[project]
name = 'CrowdfundingPlatform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.campaign-manager]
path = 'contracts/campaign-manager.clar'
clarity_version = 2
epoch = 2.5

[contracts.milestone-tracker]
path = 'contracts/milestone-tracker.clar'
clarity_version = 2
epoch = 2.5

[contracts.reward-distributor]
path = 'contracts/reward-distributor.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
